### ISSUE TITLE
Chef 13.7.16 attribute problem seen

### ISSUE THREAD

**Issue by BradBeveridge** [atomic-penguin/cookbook-krb5#37]
When I run chef client 13.7 (13.7.16-1 today), ['krb5']['packages']  is set, but the assignment to ['krb5']['client']['packages'] ends up empty.  It is not empty with 13.6 (13.6.4-1 tested.)  I have seen this on CentOS 7.4 and SUSE 12 SP2.  With the latest chef client, pre-requisite packages are not installed and then I fail later in the recipe.

This behavior does not occur with very similar attribute 'authconfig.'  The primary difference is in the initialization of the attribute -- 'packages' uses an array and 'authconfig' uses just a simple string.

Have not tested other distros.  Can you reproduce this?

**Comment by BradBeveridge** [comment]
Looks like this is the real culprit:  https://github.com/chef/chef/issues/6784

**Comment by wolf31o2** [comment]
Looks like an issue with Chef. Closing.
