### ISSUE TITLE
Enable installation of krb5 client software without pam settings

### ISSUE THREAD

**Issue by calhariz** [atomic-penguin/cookbook-krb5#38]
I have a use case, openafs servers, where I want to use this cookbook to install krb5 software without pam-krb5 being enabled.  I have not found a set of settings that would work on Debian.  For now I am trying to use the following code on my wrapper cookbook:

case node['platform_family']
when 'debian'
  node.normal['krb5']['client']['packages'] = %w(libkrb5-3 krb5-user)
end
node.normal['krb5']['client']['authconfig'] = 'true'

**Comment by wolf31o2** [comment]
I'm doing this. You can do this purely by attribute in a role, whatever.
`default['krb5']['client']['authconfig'] = '/bin/true'`

I'll add a flag to determine whether to trigger the authconfig or not. I need the libraries/daemons/etc for HDFS, and we do no system-level Kerberos, so I feel your pain. 😄
